### ISSUE TITLE
wrong date for OVH accident

### ISSUE THREAD

**Issue by rsharifnasab** [amirbagh75/The-dark-sides-of-being-a-SysAdminn#2]
OVH fire happened in Esfand 20, but [document](https://github.com/ohmydevops/The-dark-sides-of-being-a-SysAdminn/blob/main/README.md#%D9%84%DB%8C%D8%B3%D8%AA-%D8%AE%D8%A7%D8%B7%D8%B1%D8%A7%D8%AA%D9%86%D9%88%D8%B4%D8%AA%D9%87%D9%87%D8%A7%D8%A7%D8%AA%D9%81%D8%A7%D9%82%D8%A7%D8%AA) show another wrong date. (possible confusion with Arvan problem)

**Comment by ohmydevops** [comment]
حق با شماست. متشکرم
ممکنه موقع درست کردن با اروان قاطی شده باشه. الان اصلاح میکنم
